---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-operator
  namespace: keda
  labels:
    app.kubernetes.io/name: keda-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keda-operator
  endpoints:
    - port: metrics
      interval: 60s
  namespaceSelector:
    any: false
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-metrics-apiserver
  namespace: keda
  labels:
    app.kubernetes.io/name: keda-metrics-apiserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keda-metrics-apiserver
  endpoints:
    - port: http
      interval: 60s
  namespaceSelector:
    any: false
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: keda-admission-webhooks
  name: keda-admission-webhooks
  namespace: keda
spec:
  endpoints:
  - interval: 60s
    port: metrics
  namespaceSelector:
    any: false
  selector:
    matchLabels:
      app.kubernetes.io/component: admission-webhooks
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keda-olm-operator
  namespace: keda
  labels:
    name: keda-olm-operator
spec:
  selector:
    matchLabels:
      name: keda-olm-operator
  podMetricsEndpoints:
    - targetPort: 8080
      path: /metrics
      interval: 60s
