name: CI
on: [pull_request]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run unit tests
        run: make test

      - name: Run functionality tests
        run: make test-functionality

      - name: Run audit flags tests
        run: make test-audit
  statics:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Get golangci
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2
      - uses: pre-commit/action@v3.0.0

  test-build:
    name: Test Image Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container: ghcr.io/kedacore/keda-tools:1.22.5
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Go modules cache
        uses: actions/cache@v4
        with:
          path: /go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test build
        run: make docker-build
